import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react';
import { useState, useEffect, useRef } from 'react'
import Link from 'next/link'

export default function Home({ data }) {
  console.log(data);
  const [idImage, setIdImage] = useState([]);
  const refScrollContainer = useRef(null);

  const AddFav = (idInput) => {
    //check if exist
    let exist = idImage.find(item => item.id === idInput);
    if (!exist || idImage.length == 0) {
      let item = { id: idInput }
      setIdImage([...idImage, item]);
    }
  };
  const RemoveFav = (idInput) => {
    //check if exist
    let exist = idImage.find(item => item.id === idInput);
    if (exist) {
      setIdImage(idImage.filter(item => item.id != idInput));
    }
  };

  useEffect(() => {
    async function getLocomotive() {
      const Locomotive = (await import("locomotive-scroll")).default;
      new Locomotive({
        el: refScrollContainer.current,
        direction: 'horizontal',
        reloadOnContextChange: true,
        touchMultiplier: 2,
        smoothMobile: 0,
        multiplier: 1.4,
        smooth: true,
        smartphone: {
          smooth: true,
          breakpoint: 767
        },
        tablet: {
          smooth: true,
          breakpoint: 1024
        },
      });
    }

    getLocomotive();
  }, []);

  useEffect(() => {
    // storing input name
    localStorage.setItem("id", JSON.stringify(idImage));
    console.log(JSON.parse(localStorage.getItem("id")));

  }, [idImage]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main" ref={refScrollContainer} data-scroll-container>
        <Link href="/fav" className="">
          <a>My collection</a>
        </Link>

        {
          data.map((img) =>
            <div key={img.id} className="card-container" data-scroll-section>
              <div className="card-image" >
                <Image
                  className='random-image'
                  src={img.download_url + ".webp"}
                  alt={img.author}
                  width={600}
                  height={450}

                  data-scroll
                  data-scroll-speed="2"

                ></Image>
                <button onClick={() => AddFav(img.id)}>Add</button>
                <button onClick={() => RemoveFav(img.id)}>Remove</button>
              </div>
            </div>
          )
        }

      </main>

      <footer className={styles.footer}>
        <p>
          Made by passion ©JeRimes
        </p>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://picsum.photos/v2/list?limit=10`)
  const data = await res.json()
  // Pass data to the page via props
  return { props: { data } }
}